# Generated by Django 5.0.6 on 2024-06-05 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CoderAPP', '0002_estudiante'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudiante',
            name='apellido',
            field=models.CharField(max_length=30),
        ),
    ]
